### ISSUE TITLE
Support emu4crt Mednafen fork

### ISSUE THREAD

**Issue by ichigodno** [Speedvicio/MedGuiReborn#1]
Please have a look to emu4crt Mednafen fork. Emu4crt, which support native resolutions,

https://github.com/emu4crt/files

Thanks.

**Comment by Speedvicio** [comment]
Ciao.
I already know your fork, seem a great work.
I have tried the last build, could be a great idea to support also custom
Resolution in super mode.
Again compliment, see you next time.

Il 12 mar 2018 10:01 PM, "ichigodno" <notifications@github.com> ha scritto:

**Comment by ichigodno** [comment]
Just fixing ...

It does not belong to me. I just wanted you to support the mod.

All credit belongs to mednafen programmers and creator of mod: silmalik

(Meu inglês é horrível, então vai desculpando. O trabalho pertence aos programadores do mednafen e silmalik.(http://forum.arcadecontrols.com/index.php/topic,155264.0.html)

**Comment by Speedvicio** [comment]
You can simply rename emu4ctr into mednafen and my gui will recognise it,
anyway I can add the only one setting added by this fork

Il 13 mar 2018 1:37 AM, "ichigodno" <notifications@github.com> ha scritto:

**Comment by Speedvicio** [comment]
I have released a modified version of MedGui 0.94 with the support to emu4crt.

**Comment by Speedvicio** [comment]
The mod that i have applied on 0.94 still continue to work in my last release.
You can test it with emu4crt.exe by renaming the exe into mednafen.exe.

**Comment by Speedvicio** [comment]
In the last commit I have added a control at startup for emu4crt Mednafen fork.
Now you don't need to rename it into Mednafen, MedGuiR will clone and rename emu4crt.exe into mednafen.exe.
As usually the only option relative to crt res will appear on advanced settings > filter tab
