### ISSUE TITLE
Feature Request: Move sideways tabs to top

### ISSUE THREAD

**Issue by birdybro** [Speedvicio/MedGuiReborn#11]
The sideways tabs are very unintuitive, hard to read, and don't seem to have any actual reason to be designed this way as there is plenty of real estate at the top of the tab. I have to strain my neck sideways to use the tabs for probably zero actual technical or design benefit imaginable.

<img width="959" alt="8ectg2Vdw4" src="https://user-images.githubusercontent.com/16388068/93672350-77ff0a80-fa67-11ea-9646-5682de597f63.png">

It's been the primary reason I've opted to use Mednaffe instead, but with Mednaffe basically being inactive for 7 months or so, I am kinda hesitant to keep using it and am using yours now.

**Comment by Speedvicio** [comment]
the hidden top bar probably is a bug, you can enable it in side (crappy?) tab, general >  tick (or untick) text menu.
About rotated side tab, there is always a reason for a specific design, first medgui and later medguir was written in 2007 for my convenience and for a Asus eeepc70.
Old netbook and today any new netbook has 7 or 10 inch display, most of new emulator/frontend are not usable on this screen, medgui is totally usable on this screen and do put all option I had to make the sidebar vertical.
I will not change my decision to make it horizontal, i still use my old eeepc 70 and mednafen remain one of the few emulators that support old pc and win xp.
De facto in 2020 all window users can continue to use Mednafen and MedguiR (same reason that is written using net framework 2.0).

**Comment by birdybro** [comment]
That's interesting reasoning for sure, but why are drop down menus not used instead of tabs, surely drop down menus and popup config windows with top tabs (which you already have) would handle all of this the same right?

**Comment by birdybro** [comment]
What's the resolution of the screen you are using as a base reference? I think I've found good motivation to see if I can contribute a potential redesign that accounts for your use case scenario and intention

**Comment by Speedvicio** [comment]
> 
> 
> What's the resolution of the screen you are using as a base reference? I think I've found good motivation to see if I can contribute a potential redesign that accounts for your use case scenario and intention

The base res is 800x480, If you change the tabview to horizontal, all text inside the tabs will become unreadable.
Anyway all my project are distribuited under CC0-1.0 License, do all whatever you want with the code, and any contributions to the improvement of the program are welcome. 
Besides, I don't have much time to dedicate to the frontend anymore, the only changes I will make to the code will happen when some bug is reported or if the Mednafen author will add new parameters or modules to the emulator.
