### ISSUE TITLE
Mouse Cursor visibility option is broken due to a spelling mistake

### ISSUE THREAD

**Issue by SkyPirate1** [Speedvicio/MedGuiReborn#13]
The only two options should be "hidden" and "visible" but you have it save as "vinsibile" and it breaks the config file.

Also you have part of the wrong description copied into the Goat Mask Pattern option from the pixel shader in the other tab:
<img src="https://i.imgur.com/AehXAUd.png"/>

**Comment by Speedvicio** [comment]
Hello, thanks for reporting the bugs.when I have some time available to fix them

**Comment by Speedvicio** [comment]
> The only two options should be "hidden" and "visible" but you have it save as "vinsibile" and it breaks the config file.
> 
> Also you have part of the wrong description copied into the Goat Mask Pattern option from the pixel shader in the other tab: ![](https://camo.githubusercontent.com/f2187ddc933cfd0df99f48ebd9c05f69fa7044d68694fe5fba94834669c7a37b/68747470733a2f2f692e696d6775722e636f6d2f416568584155642e706e67)

Now should be fixed, try it by force update the GUI.
Thanks for reporting the bug :)

**Comment by SkyPirate1** [comment]
Thank you for fixing this.  I'm closing this issue since it is resolved but I have found another one to report.
