### ISSUE TITLE
[Feature request] Separate the bios files settings into their individual console configurations

### ISSUE THREAD

**Issue by SkyPirate1** [Speedvicio/MedGuiReborn#15]
After a bit of thought on my last bug report, I wondered why are all of the firmware settings shown for each console in the configuration tab?  Seems a bit inefficient.  If I am on psx setting I shouldn't see anything but PlayStation relevant bios options (US, JP, EU).  If I am on pce setting then only PC Engine/TG16 and Games Express (gecd) should be shown, etc.  It would at least cut down the amount of tabs on each console window.  Group firmware by hardware relation I guess is the best way to put it.

**Comment by Speedvicio** [comment]
Try this release, overwrite your existent MedGuiR executable
[MedGuiR.zip](https://github.com/Speedvicio/MedGuiReborn/files/8741504/MedGuiR.zip)
.
This should fix also [this issue](https://github.com/Speedvicio/MedGuiReborn/issues/14)

**Comment by Speedvicio** [comment]
Change the visualization of tabs on advanced setting will broke the tab order and it would force me to modify a lot of code. 
For the moment the specific bioses of each console will be highlighted, while all the others will not be editable. 
It is not an aesthetically pleasing modification but it should partially satisfy your request.
https://github.com/Speedvicio/MedGuiReborn/commit/79ddbc9eada4ab057d88f4367f87d462e09691ab
