### ISSUE TITLE
Downloading/decompress problem for .sbi patches (suggesting offline patching)

### ISSUE THREAD

**Issue by rocknard** [Speedvicio/MedGuiReborn#16]
I'm using windows xp (maybe related to incompatible 7z or internet protocols?).

A file invalid with a size of 1KB (Final Fantasy VIII disc1 ESP) is downloaded or created on:

..\MedGuiR\Patch\Psx\Sbi\02084.7z

A open box with "Waiting for extraction..." that never close.
---------------------------
The "MGRerr.log" gives me:

Sbi - get_SbiPatch:Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.
---------------------------

Well, i don't think there is any need to download the .sbi files, since their size is minimal and can be downloaded from "http://redump.org/sbi/psx/" (the entire pack). Maybe can be added to MedGui Reborn and apply offline? (to avoid the server side for conservation purposes). Yes, the option "Import  IPS/SBI/BPS patch" can do it. The "problem" is if you use a CloneCD image (.ccd/.sub), you won't need the .sbi file, but you will be nagged with the message to apply the patch.

In my case i patched the games with a .ppf to nullyfy the Libcrypt protection (or with a .LSD patch to generate a .ccd/.sub image and avoid this problem, generated with SBITools) and can't avoid the nag screen "Your PSX game needs a LaserLock patch to work properly".

Thanks.

**Comment by Speedvicio** [comment]
> I'm using windows xp (maybe related to incompatible 7z or internet protocols?).
> 
> A file invalid with a size of 1KB (Final Fantasy VIII disc1 ESP) is downloaded or created on:
> 
> ..\MedGuiR\Patch\Psx\Sbi\02084.7z
> 
> ## A open box with "Waiting for extraction..." that never close.
> The "MGRerr.log" gives me:
> 
> ## Sbi - get_SbiPatch:Invalid archive: open/read error! Is it encrypted and a wrong password was provided?
> If your archive is an exotic one, it is possible that SevenZipSharp has no signature for its format and thus decided it is TAR by mistake.
> Well, i don't think there is any need to download the .sbi files, since their size is minimal and can be downloaded from "http://redump.org/sbi/psx/" (the entire pack). Maybe can be added to MedGui Reborn and apply offline? (to avoid the server side for conservation purposes). Yes, the option "Import IPS/SBI/BPS patch" can do it. The "problem" is if you use a CloneCD image (.ccd/.sub), you won't need the .sbi file, but you will be nagged with the message to apply the patch.
> 
> In my case i patched the games with a .ppf to nullyfy the Libcrypt protection (or with a .LSD patch to generate a .ccd/.sub image and avoid this problem, generated with SBITools) and can't avoid the nag screen "Your PSX game needs a LaserLock patch to work properly".
> 
> Thanks.

The link to my server was very old, I have not updated it, probably this was the reason that the file resulted damaged.
I have also noticed that medguir already ask for download the patch, so you don't have to download patches, just answer "no" to the download request.
Anyway I have forced close the "Waiting for extraction..." message if un error occour, and i have changed the link to my server to download the patch correctly.
Can you test this version to confirm that all is ok now?
[MedGuiR.zip](https://github.com/Speedvicio/MedGuiReborn/files/8864478/MedGuiR.zip)

**Comment by rocknard** [comment]
Oh, right. How i know if medguireborn is using the ".m3u" listing the multi-cds? Since there is .bin/.cue next to .m3u (affect it to how medgui load "automatically" the next cd or must i do something when the game tell me to insert other disc?)

Thanks.

Note: i can't edit messages on my fork firefox (serpent). Sorry.

**Comment by Speedvicio** [comment]
If you have created m3u correctly, when you load it by medgui should appear
a popup that ask to load a numbered CD.
In alternative you can swap this by mednafen it self using F6/F8 keys.

Il ven 10 giu 2022, 04:11 rocknard ***@***.***> ha scritto:

**Comment by Speedvicio** [comment]
Fixed with https://github.com/Speedvicio/MedGuiReborn/commit/a147caca0b6221f2940f959eb9e83f6fd24386b4 commit.
Thx @rocknard for report the bug :)
