### ISSUE TITLE
MedGui.Reborn.v0.120.full.zip flagged as malware

### ISSUE THREAD

**Issue by vico93** [Speedvicio/MedGuiReborn#18]
Strangely, 0.120 binary's zip file was flagged as `PUA:AndroidOS/ZkarletPlush` by Windows Defender. Seems to not be serious enough to automatically remove the file (i was able to unzip it normally via 7zip), but it was also flagged by other AV products [in VirusTotal](https://www.virustotal.com/gui/file/969aea8923d6ac3c4937229c8da4f581748fab063d66d512ee96af3126f58557).

Any idea of why it was marked in that way?

**EDIT**: Seems like files inside the .zip were also flagged:

- `MedGui Reborn Wizard.exe` ([VirusTotal](https://www.virustotal.com/gui/file/0496c5a86a621a544f36897b4ba837ab315cfdd2f883599a708d3dce2d87e22e));
- `MedGuiR.exe` ([VirusTotal](https://www.virustotal.com/gui/file/c5ad9ee911a1a45539a18b6adfafceb8a61ef2bec02b5922be9ad70bb35733d6));
- `MedInstR.exe` ([VirusTotal](https://www.virustotal.com/gui/file/775fde98c705a434e3fe31eab540c67b4c7d4f344e8ae4f61a8fb1fdaf7e61c5));
- `MetroMed.exe` ([VirusTotal](https://www.virustotal.com/gui/file/4e9ea035de66b00162d5e26cbd698c9dbea34757a028b324cc6d913c31c1fb76));
- `Spismo.exe` ([VirusTotal](https://www.virustotal.com/gui/file/225ac225a0547813ab808c13c068b33e8fe3098ffe68de6931a076b49dda8a0a)).

**Comment by Speedvicio** [comment]
Oddly, it forgot to mark MedPad.exe as a virus-infected file :D
Anyway all report probably is related to executables compiled with visual studio, they are all false positives, I think the antiviruses in question will use euroustic functions to mark them as viruses.
