### ISSUE TITLE
MedGui Reborn doesn't save my joypad configuration

### ISSUE THREAD

**Issue by buruto** [Speedvicio/MedGuiReborn#19]
I have configured a joypad but MedGui Reborn doesn't save my joypad configuration on close and also there is no save button and no menu.

How am I supposed to play the game with my joypad configuration?

**Comment by Speedvicio** [comment]
> I have configured a joypad but MedGui Reborn doesn't save my joypad configuration on close and also there is no save button and no menu.
> 
> How am I supposed to play the game with my joypad configuration?

Can you explain what step are you following to setup the pad?

Anyway you can always configure the pad by mednafen itself.
Launch a game, press CTRL SHIFT 1 on the left of your keyboard, and follow the instruction on the bottom of emulated game.

**Comment by buruto** [comment]
> > I have configured a joypad but MedGui Reborn doesn't save my joypad configuration on close and also there is no save button and no menu.
> > How am I supposed to play the game with my joypad configuration?
> 
> Can you explain what step are you following to setup the pad?
> 
> Anyway you can always configure the pad by mednafen itself. Launch a game, press CTRL SHIFT 1 on the left of your keyboard, and follow the instruction on the bottom of emulated game.

1. Right click the game that I want to play to show a context menu.
2. In the context menu left click "Configure Joypad"
3. "MedPad - Mednafen Pad Configurator" window appears without a menu and save button.
4. In this window I can choose "DualShock" in the "Device" drop down list and map my keyboard to DualShock buttons.
5. After I finished doing this I want to save the new pad configuration that I just made but as I said earlier there is no save button and not even File->Save menu because there is no a menu at all in the "MedPad - Mednafen Pad Configurator" window.
6. So I close the "MedPad - Mednafen Pad Configurator" window by left clicking the red cross button on the top right corner, a button that every window has in Microsoft Windows operarting systems.
7. I expected that the configuration that I made will be automatically save on close but it doesn't. When I play the game, all binds and maps that I made are gone.

**Comment by Speedvicio** [comment]
You need to select first your device on the upper list, if no one pad is detected, you need to check direct input checkbox.
If your pad is detected, you can test it by the cross on the right side of medpad.
After, you need to select every input on the list, and press the relative input\direction to assign.
When you finished, close medpad and the input will be saved.

I have posted in the past a video on YouTube:

https://www.youtube.com/watch?v=hdc1PLYw0ho

**Comment by buruto** [comment]
> You need to select first your device on the upper list, if no one pad is detected, you need to check direct input checkbox. If your pad is detected, you can test it by the cross on the right side of medpad. After, you need to select every input on the list, and press the relative input\direction to assign. When you finished, close medpad and the input will be saved.
> 
> I have posted in the past a video on YouTube:
> 
> https://www.youtube.com/watch?v=hdc1PLYw0ho

Only the Mouse appears in the "Available Pad" list. I ticked the DInput checkbox but my keyboard still does not appear in the "Available Pad" list.

Why only the Mouse appears in the "Available Pad" list?

**Comment by Speedvicio** [comment]
then you want to set keyboard input, not a joypad?
If you want to set the keyboard you do not need to press anythings.
Select by mouse every single input to assign on the left list and press the key to assign.
I have tested now the procedure and it work fine.
Remember that mednafen for psx use as default controller the traditional digital gamepad, if you want to use the dualshock pad you need also to set it as default controller, you can do it by medguir on advanced emu setting, on the relative gamepad section or by mednafen itself, launching a game and swapping the available input by pressing the combo CTRL SHIFT 1.
In the previous post i have wrongly write the combo to assign input, the correct is ALT SHIFT 1.

**Comment by buruto** [comment]
> then you want to set keyboard input, not a joypad? If you want to set the keyboard you do not need to press anythings. Select by mouse every single input to assign on the left list and press the key to assign. I have tested now the procedure and it work fine. Remember that mednafen for psx use as default controller the traditional digital gamepad, if you want to use the dualshock pad you need also to set it as default controller, you can do it by medguir on advanced emu setting, on the relative gamepad section or by mednafen itself, launching a game and swapping the available input by pressing the combo CTRL SHIFT 1. In the previous post i have wrongly write the combo to assign input, the correct is ALT SHIFT 1.

So to the play the game with my keyboard am I must use ALT SHIFT 1 while the game is running if I understood you correctly?

**Comment by Speedvicio** [comment]
if you want to set the pad by mednafen you need firstly to launch the game.
Example to set dualshock on psx:
Launch a psx game
Swap the controller type by pressing CTRL SHIFT 1 (follow the bottom screen instructions)
Set the input by pressing ALT SHIFT 1 (follow the bottom screen instructions)

Done

When you close (not force close) the emulator, your setting will be saved by emulator

**Comment by buruto** [comment]
> if you want to set the pad by mednafen you need firstly to launch the game. Example to set dualshock on psx: Launch a psx game Swap the controller type by pressing CTRL SHIFT 1 (follow the bottom screen instructions) Set the input by pressing ALT SHIFT 1 (follow the bottom screen instructions)
> 
> Done
> 
> When you close (not force close) the emulator, your setting will be saved by emulator

So I need to use the Mednafen itself and not MedGui Reborn? I will try and let you know if this works for me or not. Now I have time to try this method.

**Comment by Speedvicio** [comment]
You can use what do you prefer, personally i use mednafen because is more speedly to set the input.
Now i close the the issue because it's not related to a bug, if you need help, use the discord channell, is more user friendly.
