### ISSUE TITLE
Unable to boot Tomb Raider

### ISSUE THREAD

**Issue by buruto** [Speedvicio/MedGuiReborn#21]
When I try to open the ccd file I see the following error:

> ---------------------------
Mednafen(1.31.0-UNSTABLE) Error
---------------------------
Error opening CD: Garbage subchannel Q data detected(excessively large jump in AMSF: 29:17:54 -> 29:15:53)
---------------------------
OK   
---------------------------

And the ccd file that I am trying to open is:

> [CloneCD]
> Version=3
> 
> [Disc]
> TocEntries=60
> Sessions=1
> DataTracksScrambled=0
> CDTextLength=0
> 
> [Session 1]
> PreGapMode=2
> PreGapSubC=1
> 
> [Entry 0]
> Session=1
> Point=0xa0
> ADR=0x01
> Control=0x04
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=1
> PSec=32
> PFrame=0
> PLBA=6750
> 
> [Entry 1]
> Session=1
> Point=0xa1
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=57
> PSec=0
> PFrame=0
> PLBA=256350
> 
> [Entry 2]
> Session=1
> Point=0xa2
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=59
> PSec=24
> PFrame=23
> PLBA=267173
> 
> [Entry 3]
> Session=1
> Point=0x01
> ADR=0x01
> Control=0x04
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=0
> PSec=2
> PFrame=0
> PLBA=0
> 
> [Entry 4]
> Session=1
> Point=0x02
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=29
> PSec=17
> PFrame=54
> PLBA=131679
> 
> [Entry 5]
> Session=1
> Point=0x03
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=32
> PSec=34
> PFrame=22
> PLBA=146422
> 
> [Entry 6]
> Session=1
> Point=0x04
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=33
> PSec=38
> PFrame=20
> PLBA=151220
> 
> [Entry 7]
> Session=1
> Point=0x05
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=35
> PSec=41
> PFrame=59
> PLBA=160484
> 
> [Entry 8]
> Session=1
> Point=0x06
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=37
> PSec=41
> PFrame=70
> PLBA=169495
> 
> [Entry 9]
> Session=1
> Point=0x07
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=38
> PSec=58
> PFrame=69
> PLBA=175269
> 
> [Entry 10]
> Session=1
> Point=0x08
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=39
> PSec=54
> PFrame=60
> PLBA=179460
> 
> [Entry 11]
> Session=1
> Point=0x09
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=41
> PSec=3
> PFrame=4
> PLBA=184579
> 
> [Entry 12]
> Session=1
> Point=0x0a
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=41
> PSec=43
> PFrame=10
> PLBA=187585
> 
> [Entry 13]
> Session=1
> Point=0x0b
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=43
> PSec=2
> PFrame=31
> PLBA=193531
> 
> [Entry 14]
> Session=1
> Point=0x0c
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=43
> PSec=10
> PFrame=68
> PLBA=194168
> 
> [Entry 15]
> Session=1
> Point=0x0d
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=43
> PSec=25
> PFrame=67
> PLBA=195292
> 
> [Entry 16]
> Session=1
> Point=0x0e
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=43
> PSec=32
> PFrame=70
> PLBA=195820
> 
> [Entry 17]
> Session=1
> Point=0x0f
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=43
> PSec=45
> PFrame=0
> PLBA=196725
> 
> [Entry 18]
> Session=1
> Point=0x10
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=43
> PSec=56
> PFrame=3
> PLBA=197553
> 
> [Entry 19]
> Session=1
> Point=0x11
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=44
> PSec=34
> PFrame=66
> PLBA=200466
> 
> [Entry 20]
> Session=1
> Point=0x12
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=45
> PSec=17
> PFrame=55
> PLBA=203680
> 
> [Entry 21]
> Session=1
> Point=0x13
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=45
> PSec=43
> PFrame=4
> PLBA=205579
> 
> [Entry 22]
> Session=1
> Point=0x14
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=47
> PSec=11
> PFrame=49
> PLBA=212224
> 
> [Entry 23]
> Session=1
> Point=0x15
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=48
> PSec=5
> PFrame=66
> PLBA=216291
> 
> [Entry 24]
> Session=1
> Point=0x16
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=48
> PSec=47
> PFrame=8
> PLBA=219383
> 
> [Entry 25]
> Session=1
> Point=0x17
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=49
> PSec=50
> PFrame=46
> PLBA=224146
> 
> [Entry 26]
> Session=1
> Point=0x18
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=50
> PSec=48
> PFrame=15
> PLBA=228465
> 
> [Entry 27]
> Session=1
> Point=0x19
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=51
> PSec=3
> PFrame=43
> PLBA=229618
> 
> [Entry 28]
> Session=1
> Point=0x1a
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=51
> PSec=40
> PFrame=31
> PLBA=232381
> 
> [Entry 29]
> Session=1
> Point=0x1b
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=51
> PSec=47
> PFrame=32
> PLBA=232907
> 
> [Entry 30]
> Session=1
> Point=0x1c
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=51
> PSec=54
> PFrame=33
> PLBA=233433
> 
> [Entry 31]
> Session=1
> Point=0x1d
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=1
> PFrame=33
> PLBA=233958
> 
> [Entry 32]
> Session=1
> Point=0x1e
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=8
> PFrame=34
> PLBA=234484
> 
> [Entry 33]
> Session=1
> Point=0x1f
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=16
> PFrame=32
> PLBA=235082
> 
> [Entry 34]
> Session=1
> Point=0x20
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=23
> PFrame=33
> PLBA=235608
> 
> [Entry 35]
> Session=1
> Point=0x21
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=32
> PFrame=71
> PLBA=236321
> 
> [Entry 36]
> Session=1
> Point=0x22
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=42
> PFrame=38
> PLBA=237038
> 
> [Entry 37]
> Session=1
> Point=0x23
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=50
> PFrame=10
> PLBA=237610
> 
> [Entry 38]
> Session=1
> Point=0x24
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=52
> PSec=57
> PFrame=24
> PLBA=238149
> 
> [Entry 39]
> Session=1
> Point=0x25
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=53
> PSec=14
> PFrame=20
> PLBA=239420
> 
> [Entry 40]
> Session=1
> Point=0x26
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=53
> PSec=21
> PFrame=21
> PLBA=239946
> 
> [Entry 41]
> Session=1
> Point=0x27
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=53
> PSec=28
> PFrame=22
> PLBA=240472
> 
> [Entry 42]
> Session=1
> Point=0x28
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=53
> PSec=44
> PFrame=28
> PLBA=241678
> 
> [Entry 43]
> Session=1
> Point=0x29
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=53
> PSec=54
> PFrame=68
> PLBA=242468
> 
> [Entry 44]
> Session=1
> Point=0x2a
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=1
> PFrame=69
> PLBA=242994
> 
> [Entry 45]
> Session=1
> Point=0x2b
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=8
> PFrame=69
> PLBA=243519
> 
> [Entry 46]
> Session=1
> Point=0x2c
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=18
> PFrame=7
> PLBA=244207
> 
> [Entry 47]
> Session=1
> Point=0x2d
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=26
> PFrame=31
> PLBA=244831
> 
> [Entry 48]
> Session=1
> Point=0x2e
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=36
> PFrame=22
> PLBA=245572
> 
> [Entry 49]
> Session=1
> Point=0x2f
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=43
> PFrame=23
> PLBA=246098
> 
> [Entry 50]
> Session=1
> Point=0x30
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=50
> PFrame=24
> PLBA=246624
> 
> [Entry 51]
> Session=1
> Point=0x31
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=54
> PSec=57
> PFrame=25
> PLBA=247150
> 
> [Entry 52]
> Session=1
> Point=0x32
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=55
> PSec=13
> PFrame=21
> PLBA=248346
> 
> [Entry 53]
> Session=1
> Point=0x33
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=55
> PSec=20
> PFrame=21
> PLBA=248871
> 
> [Entry 54]
> Session=1
> Point=0x34
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=55
> PSec=27
> PFrame=21
> PLBA=249396
> 
> [Entry 55]
> Session=1
> Point=0x35
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=55
> PSec=34
> PFrame=22
> PLBA=249922
> 
> [Entry 56]
> Session=1
> Point=0x36
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=55
> PSec=43
> PFrame=42
> PLBA=250617
> 
> [Entry 57]
> Session=1
> Point=0x37
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=55
> PSec=50
> PFrame=43
> PLBA=251143
> 
> [Entry 58]
> Session=1
> Point=0x38
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=56
> PSec=0
> PFrame=22
> PLBA=251872
> 
> [Entry 59]
> Session=1
> Point=0x39
> ADR=0x01
> Control=0x00
> TrackNo=0
> AMin=0
> ASec=0
> AFrame=0
> ALBA=-150
> Zero=0
> PMin=56
> PSec=7
> PFrame=23
> PLBA=252398
> 
> [TRACK 1]
> MODE=2
> INDEX 1=0
> 
> [TRACK 2]
> MODE=0
> INDEX 0=131529
> INDEX 1=131679
> 
> [TRACK 3]
> MODE=0
> INDEX 1=146422
> 
> [TRACK 4]
> MODE=0
> INDEX 1=151220
> 
> [TRACK 5]
> MODE=0
> INDEX 1=160484
> 
> [TRACK 6]
> MODE=0
> INDEX 1=169495
> 
> [TRACK 7]
> MODE=0
> INDEX 1=175269
> 
> [TRACK 8]
> MODE=0
> INDEX 1=179460
> 
> [TRACK 9]
> MODE=0
> INDEX 1=184579
> 
> [TRACK 10]
> MODE=0
> INDEX 1=187585
> 
> [TRACK 11]
> MODE=0
> INDEX 1=193531
> 
> [TRACK 12]
> MODE=0
> INDEX 1=194168
> 
> [TRACK 13]
> MODE=0
> INDEX 1=195292
> 
> [TRACK 14]
> MODE=0
> INDEX 1=195820
> 
> [TRACK 15]
> MODE=0
> INDEX 1=196725
> 
> [TRACK 16]
> MODE=0
> INDEX 1=197553
> 
> [TRACK 17]
> MODE=0
> INDEX 1=200466
> 
> [TRACK 18]
> MODE=0
> INDEX 1=203680
> 
> [TRACK 19]
> MODE=0
> INDEX 1=205579
> 
> [TRACK 20]
> MODE=0
> INDEX 1=212224
> 
> [TRACK 21]
> MODE=0
> INDEX 1=216291
> 
> [TRACK 22]
> MODE=0
> INDEX 1=219383
> 
> [TRACK 23]
> MODE=0
> INDEX 1=224146
> 
> [TRACK 24]
> MODE=0
> INDEX 1=228465
> 
> [TRACK 25]
> MODE=0
> INDEX 1=229618
> 
> [TRACK 26]
> MODE=0
> INDEX 1=232381
> 
> [TRACK 27]
> MODE=0
> INDEX 1=232907
> 
> [TRACK 28]
> MODE=0
> INDEX 1=233433
> 
> [TRACK 29]
> MODE=0
> INDEX 1=233958
> 
> [TRACK 30]
> MODE=0
> INDEX 1=234484
> 
> [TRACK 31]
> MODE=0
> INDEX 1=235082
> 
> [TRACK 32]
> MODE=0
> INDEX 1=235608
> 
> [TRACK 33]
> MODE=0
> INDEX 1=236321
> 
> [TRACK 34]
> MODE=0
> INDEX 1=237038
> 
> [TRACK 35]
> MODE=0
> INDEX 1=237610
> 
> [TRACK 36]
> MODE=0
> INDEX 1=238149
> 
> [TRACK 37]
> MODE=0
> INDEX 1=239420
> 
> [TRACK 38]
> MODE=0
> INDEX 1=239946
> 
> [TRACK 39]
> MODE=0
> INDEX 1=240472
> 
> [TRACK 40]
> MODE=0
> INDEX 1=241678
> 
> [TRACK 41]
> MODE=0
> INDEX 1=242468
> 
> [TRACK 42]
> MODE=0
> INDEX 1=242994
> 
> [TRACK 43]
> MODE=0
> INDEX 1=243519
> 
> [TRACK 44]
> MODE=0
> INDEX 1=244207
> 
> [TRACK 45]
> MODE=0
> INDEX 1=244831
> 
> [TRACK 46]
> MODE=0
> INDEX 1=245572
> 
> [TRACK 47]
> MODE=0
> INDEX 1=246098
> 
> [TRACK 48]
> MODE=0
> INDEX 1=246624
> 
> [TRACK 49]
> MODE=0
> INDEX 1=247150
> 
> [TRACK 50]
> MODE=0
> INDEX 1=248346
> 
> [TRACK 51]
> MODE=0
> INDEX 1=248871
> 
> [TRACK 52]
> MODE=0
> INDEX 1=249396
> 
> [TRACK 53]
> MODE=0
> INDEX 1=249922
> 
> [TRACK 54]
> MODE=0
> INDEX 1=250617
> 
> [TRACK 55]
> MODE=0
> INDEX 1=251143
> 
> [TRACK 56]
> MODE=0
> INDEX 1=251872
> 
> [TRACK 57]
> MODE=0
> INDEX 1=252398

I read that ccd files should be supported so why I get this error when I try to open the ccd file instead of just booting the game?

I even tried a stable Mednafen but still the same error pops up instead of booting the game.

Other PSX emulators that I tried have no problem booting and playing this game.

Some of them are DuckStation, PCSX-Redux, Xebra, pSXfin 1.13, NO$PSX and even BizHawk.

**Comment by Speedvicio** [comment]
Mednafen perform a correction on subchannel to prevent errors, but it is less forgiving when it comes to doing with a bad dump compared to other less accurate emulators.
You should to try to load another better dump.
Anyway it is not a frontend bug, I will close the issue.
