### ISSUE TITLE
input.autofirefreq (Auto-fire frequency) isn't saved in a per-game configuration

### ISSUE THREAD

**Issue by Skalt711** [Speedvicio/MedGuiReborn#22]
Self-explanatory title. Per-console input.autofirefreq isn't written as well (Not a big deal), while the global input.autofirefreq is saved correctly.

I can tell it's not Mednafen's issue since manually writing input.autofirefreq into a per-game config allows the setting to be saved correctly.

**Comment by Speedvicio** [comment]
The only parameters saved on per-system and per-game config are the followed:

; << Sound Config >>
; << Video Config >>
; << Filters Config >>
; << Bios Config >>
; << Specific Console Config >>

All others will be readed from main mednafen config.

**Comment by Speedvicio** [comment]
Closed
