### ISSUE TITLE
add new frontend bundled latest cores for Android phone

### ISSUE THREAD

**Issue by soundsnow** [Speedvicio/MedGuiReborn#23]
like jzIntvImGui for jzintv - an Intellivision emulator frontend
https://github.com/jenergy/jzIntvImGui/releases
Contains Windows, Linux and Android versions
Lock portrait or landscape

**Comment by Speedvicio** [comment]
Sorry I do not understand.
What is your request?

**Comment by Speedvicio** [comment]
> any plans to port MedGuiReborn to Linux and Android in the future?

I'm not mednafen developer, from my knowledge there are no success on android build, there are any fork on android, for example retroarch has many forked mednafen module.
About a compatible frontend for Linux, there is mednaffe, you can found it on github
