### ISSUE TITLE
there are no roms in the list despite i chose a rom folder

### ISSUE THREAD

**Issue by ExGuestCJ** [Speedvicio/MedGuiReborn#24]

**Comment by Speedvicio** [comment]
What folder are you using to store yours games?

**Comment by ExGuestCJ** [comment]
a folder named "roms" with subfolders with snes, nes, mega drive, game boy (normal, color and advance), and n64

**Comment by Speedvicio** [comment]
On side medgui tabs there is a section called rom path 1, select that and on default rom  point your rom path.
After that on top left medgui there is a combo box with a list of selectable folder, select Def and wait for recursive scan.
I advice you, recursive scan for all that rom  is not a good idea, depends how many roms you have inside it will require a lot of time.

**Comment by Speedvicio** [comment]
If the problem is caused by missing DLL (due to antivir behaviour), this is not a bug.

**Comment by ExGuestCJ** [comment]
there is an error saying "def.csv has unrecognized files or empty values" (and my antivirus doesnt detect it as a virus so i dont know what happens)

**Comment by Speedvicio** [comment]
> there is an error saying "def.csv has unrecognized files or empty values" (and my antivirus doesnt detect it as a virus so i dont know what happens)

That message is relative to default empty or missing list, if you do not scan a rom folder medgui can't save a .csv file useful to load a list of rom.

For my opinion this is not a bug, i 'll close for now this issue.

**Comment by Speedvicio** [comment]
Probably I have found and solved the bug.
It was caused by nested empty folder on recursive scan.
