### ISSUE TITLE
(ignore last issue) my antivirus detects some dll files from the zip as troyans

### ISSUE THREAD

**Issue by ExGuestCJ** [Speedvicio/MedGuiReborn#25]

**Comment by Speedvicio** [comment]
What DLL are detected as trans and what antivirus are you using?

All file inside medgui archive are clean, probably that allert is a false positive

**Comment by ExGuestCJ** [comment]
probably thats why there is a message saying that i need to download the full package despite i did so

**Comment by ExGuestCJ** [comment]
also its proxy7z.dll

**Comment by Speedvicio** [comment]
> also its proxy7z.dll

that dll is a wrapper to 7z with plugin support to zstd algorithm.
https://www.tc4shell.com/en/7zip/proxy7z/
It is clean, and all alerts is false positive.
