### ISSUE TITLE
ability to scrape multiple? library?

### ISSUE THREAD

**Issue by jjfmz42015** [Speedvicio/MedGuiReborn#4]
Ability to scrape more that one title at at time? meaning dont have to click on title then click on scrape.

**Comment by Speedvicio** [comment]
As described on theganesdatabase forum, the API permit limited query per month:
https://forums.thegamesdb.net/viewtopic.php?t=690#p1441

I have not implemented fullset auto scrape function due to this limit, but i could consider to permit the fullset auto download of boxart from my personal server.

**Comment by jjfmz42015** [comment]
I was not aware/ thinking of limit. That being known I would leave as is.


Thanks for the nice front end.

**Comment by Speedvicio** [comment]
> 
> 
> I was not aware/ thinking of limit. That being known I would leave as is.
> 
> Thanks for the nice front end.

I have added batch download of BoxArt from my server, you can tick checkbox under the download button, to sift through all the games on the list and download the missing covers.
