### ISSUE TITLE
no-intro dat status issues

### ISSUE THREAD

**Issue by jjfmz42015** [Speedvicio/MedGuiReborn#5]
No-intro dat status malfunction.

Nost no-intro roms show ok howerver some that should say ok are showing ?

example

game name="1941 - Counter Attack (Japan)">
		<description>1941 - Counter Attack (Japan)</description>
		<rom name="1941 - Counter Attack (Japan).pce" size="1048576" crc="8C4588E2" md5="30686DBA4795521174658DE2492E0046" sha1="66873B0E0CC699AA75DAF06A3F74C0508037E605"/>

**Comment by Speedvicio** [comment]
Can you explain better?

**Comment by jjfmz42015** [comment]
that rom is one of many roms that are proper but in med gui get a status ? not status ok even though it is ok.


Do you know what I mean?

**Comment by Speedvicio** [comment]
Where have you get that rom?
I have a no intro dump and it seem ok
![immagine](https://user-images.githubusercontent.com/13048199/67593442-697a7700-f762-11e9-8666-7cf58378a04c.png)

**Comment by jjfmz42015** [comment]
hmmm that is interesting. I verified with clrmamepro, i manually checked size and crc of mine and i get ?

**Comment by Speedvicio** [comment]
the database used by medgui is almost updated but in particular that rom is not touched since 2011, i think is not a proper rom.
You can retrieve a proper set on archive.org or on planetemu.

**Comment by jjfmz42015** [comment]
believe it or not mine is proper. dont know why this is happening.

Im only so sure its proper as I re audited my roms after this, then when and redownloaded from trusted sources same issue then reaudited myself using dats same issue, then audited with the dat you included same issue then manually verified the crc and file lenght but still same issue.


must be something weird on my system

**Comment by Speedvicio** [comment]
Try to update database , could be the dat on medguir folder is damaged.
![immagine](https://user-images.githubusercontent.com/13048199/67594303-4f419880-f764-11e9-8285-1f9e15274b5e.png)

If you join discord channel i could help you by remote access to verify the error.

**Comment by jjfmz42015** [comment]
I tried replacing the day same result weird. I'll delete and redo everything and see what happens. I'm so lost now lol.

**Comment by jjfmz42015** [comment]
ok

deleted everything. when i installed just SGX as pce they all showed ok. then added my pce roms rebuilt using both all sgx back to ?


seems sgx and pce can not co exist?

**Comment by jjfmz42015** [comment]
so verified again. clean verified no intro pce set & clean no intro sgx set. put all in same rom folder.

fresh copy of mednafen, fresh med gui. all sgx have ? not ok.


if only sgx all ok.

**Comment by Speedvicio** [comment]
Sgx, pce and pc engine CD can coexist.
You can also put all supported mednafen file into a folder and medgui will recognize all.
Is the first time I heard a similar issue. 
Let me try to test a fresh medguir installation, could be verify problems with a clean medguir setup

**Comment by jjfmz42015** [comment]
Strange. honestly if i do only one or the other its fine but both and my sgx goes ?

fresh try.

Ill try on another machine later.

**Comment by jjfmz42015** [comment]
so. if i do a clean install i have this problem on all windows pcs.

however, if i use the internal updater to update no intro dats problem goes away. so then i re downloaded 108 to make sure my copy wasnt the issue and problem came back, so then i ran 108 updated dat files then i replaced bundled dat files in the zip with the new ones, now no matter where i install works fine.


kinda weird but not a bug. as long as user updates the dats
