### ISSUE TITLE
box art for 1st item not shown on load

### ISSUE THREAD

**Issue by jjfmz42015** [Speedvicio/MedGuiReborn#6]
Open medgui, the title that it is on at start up will not show its box art till you select something else then reselect.

**Comment by Speedvicio** [comment]
Is not a bug, when will load a list no row will be selected then no boxart can't be loaded, MedGui load cover from a selected game.

**Comment by jjfmz42015** [comment]
on initial load first title in list is selected.

not a bug though i agree.
